
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jul 07 20:13:51 ART 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Si = 7;
  public static final int Fin = 18;
  public static final int Leer = 21;
  public static final int Numero = 20;
  public static final int ParentesisApertura = 10;
  public static final int Entero = 6;
  public static final int Identificador = 3;
  public static final int Inicio = 17;
  public static final int Coma = 15;
  public static final int PuntoYComa = 4;
  public static final int Programa = 2;
  public static final int Variables = 13;
  public static final int Funcion = 16;
  public static final int Sino = 8;
  public static final int EOF = 0;
  public static final int Equivalencia = 9;
  public static final int Escribir = 22;
  public static final int Entonces = 5;
  public static final int error = 1;
  public static final int Modulo = 19;
  public static final int Asignacion = 12;
  public static final int ParentesisCierre = 11;
  public static final int DosPuntos = 14;
}

